
services:
  api:
    build: ./python  # 既にビルド済みのAPIイメージ
    ports:
      - "8000:8000"
    environment:
      - FRONT_URL=http://localhost:3000
      - PORT=8000
    networks:
      - mercari-net

  web:
    image: build2024/web:latest  # 既にビルド済みのフロントエンドイメージ
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - mercari-net

networks:
  mercari-net:
    driver: bridge
